# Generated by Claude (claude-sonnet-4-5-20250929)
# Date: 2025-11-21

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chisquare

# Load data
df = pd.read_csv('sample.txt', header=None, names=['line'])

# Count frequencies
counts = df['line'].value_counts().sort_index()

# Stats
expected = len(df) / len(counts)
chi2, p_value = chisquare(counts.values)

print(f"Total samples: {len(df)}")
print(f"Expected per line: {expected:.1f}")
print(f"Actual - Min: {counts.min()}, Max: {counts.max()}, Mean: {counts.mean():.1f}")
print(f"Chi-square: {chi2:.2f}, p-value: {p_value:.4f}")

# Plot
fig, ax = plt.subplots(figsize=(12, 6))
ax.bar(counts.index, counts.values, width=1.0)
ax.axhline(y=expected, color='r', linestyle='--', label=f'Expected: {expected:.1f}')
ax.set_xlabel('Line Number')
ax.set_ylabel('Frequency')
ax.set_title('Reservoir Sampling Distribution')

# Add stats text
stats_text = f"n={len(df)}\nχ²={chi2:.2f}\np={p_value:.4f}\nRange: [{counts.min()}, {counts.max()}]"
ax.text(0.02, 0.98, stats_text, transform=ax.transAxes,
        verticalalignment='top', fontfamily='monospace',
        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

ax.legend()
plt.tight_layout()
plt.savefig('distribution.png', dpi=100)
plt.show()
